legged_unitree_hw:
  loop_frequency: 800
  cycle_time_error_threshold: 0.002
  thread_priority: 95
  power_limit: 7
  contact_threshold: 40

udp_to_controller:
  controller_ip: 127.0.0.1
  own_port: 8872

udp:
  mcu_ip: 192.168.123.110
  port_to_mcu: 8881
  port_to_sdk: 8871

UnitreeGripperYN: true